### ISSUE TITLE
Batchloader implementation not called (yet)

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/graphql-maven-plugin-project#64]
Etienne,

Please recall our conversation here.
https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/58
The part regarding the batchloader.
I know, that I had something working with 1.11.1
This was called.
```
 @Override
    public List<ShortnameResponseMM> batchLoader(List<Long> keys, BatchLoaderEnvironment batchLoaderEnvironment) {
        List<LocationShortnameDTO> shortnameList = aggregatorLocationService.getLocationShortnamesByLocationIds(keys);
        List<ShortnameResponseMM> result = new ArrayList();
        //code which maps shortnameList into result in the order of keys.
        return result;
    }
```

But now with 1.11.2 it's not.
I am building with
```
<generateDeprecatedRequestResponse>false</generateDeprecatedRequestResponse>
<separateUtilityClasses>true</separateUtilityClasses>
<addRelayConnections>true</addRelayConnections>
<generateBatchLoaderEnvironment>true</generateBatchLoaderEnvironment>
```

I don't see DataFetchersDelegateShortnameResponseMM get called in GraphQLDataFetchers.
Only  in BatchLoaderDelegateShortnameResponseMMImpl

I am not sure, where I can use this. The sample code in the javadoc part is not clear to me.
It says
```
 * &#64;Override
 * public CompletableFuture<List<ShortnameResponseMM>> friends(DataFetchingEnvironment environment, DataLoader<java.lang.Long, ShortnameResponseMM> dataLoader,
 * 		ShortnameResponseMM source) {
 * 	logger.debug("Executing characterImpl.friends, with this character: {}", source.getId().toString());
 * 	List<java.lang.Long> friendIds = graphQLUtil
 * 			.convertListByteArrayToList(characterRepository.findFriendsId(source.getId()));
 * 	return dataLoader.loadMany(friendIds);
 * }
```
But I don't see CompletableFuture<List<ShortnameResponseMM>> anywhere in the project.

I haven't found the missing link in your sample code or documentation. 
Please could you point me into the right direction?

**Comment by mheidt** [comment]
This is part of the generated code in GraphQLDataFetchers:

`dataFetchingEnvironment.getDataLoader("LocationMM");`

but the dataFetchingEnvironment.getDataLoader() is empty

Do you expect the user to register the batchloaders him- or herself?

for example in a customized GraphQLInvocation ?

@Override
public CompletableFuture<ExecutionResult> invoke(GraphQLInvocationData graphQLInvocationData,
                                                     WebRequest webRequest) {
        ExecutionInput.Builder executionInputBuilder = ExecutionInput.newExecutionInput()
            .query( graphQLInvocationData.getQuery())
            .operationName(graphQLInvocationData.getOperationName())
            .variables(graphQLInvocationData.getVariables());
        
        DataLoaderRegistry dataLoaderRegistry = new DataLoaderRegistry();
        //dataLoaderRegistry.register("locationMM", null); how?

        executionInputBuilder.dataLoaderRegistry(dataLoaderRegistry);
        executionInputBuilder.context(dataLoaderRegistry);
        ExecutionInput executionInput = executionInputBuilder.build();

        return graphQL.executeAsync(executionInput);
}

**Comment by etienne-sf** [comment]
I'm sorry, but it's quite complex to understand.

Some answers to your questions:

> Do you expect the user to register the dataloaders him- or herself?
No. They are discovered by the GraphQLProvider.dataLoaderRegistry() method. Then they are retrieved by the generated code, by the line ```dataFetchingEnvironment.getDataLoader("LocationMM");``` 
I checked in my samples, and it's not empty. It contains a valid data loader.



Did you follow the sample I gave to you ?

I just checked that it works Ok. The batchLoader is called. 
Don't update the generated code.

**Comment by mheidt** [comment]
Can you tell me, where the dataloader is called? the part, that collects the Id, before the batchloader is using them.
I read your code, but didn't build it.

**Comment by mheidt** [comment]
HM...
applicationContext.getBeansOfType(BatchLoaderDelegate.class) is empty...i will investigate...

**Comment by mheidt** [comment]
Ok, that is because my BatchloaderDelegates are of type BatchLoaderDelegateWithContext.

**Comment by mheidt** [comment]
And I don't understand, why it doesn't getBeansOfType should consider subclasses as well.
This person had simular issues
https://stackoverflow.com/questions/40857277/using-spring-applicationcontext-getbeansoftype-does-not-returns-all-beans-if-dif
But that's more related with classloader. Not sure if that's the case here
Maybe inherited generic interfaces are the issue.

I would solve it, giving the BatchloaderImpls an annotation and search for the annotation.

**Comment by etienne-sf** [comment]
Ok, I understand your point.

And you're right, there is a regression here.  You spotted the good line, in the generated ```GraphQLProvider.dataLoaderRegistry()``` method:

```
		for (BatchLoaderDelegate<?, ?> batchLoaderDelegate : applicationContext
				.getBeansOfType(BatchLoaderDelegate.class).values()) {
```

should be replaced by:

```
		for (BatchLoaderDelegateWithContext<?, ?> batchLoaderDelegate : applicationContext
				.getBeansOfType(BatchLoaderDelegateWithContext.class).values()) {
```

Then, the BatchLoader are properly loaded.


Hum, I made my previous check from the tutorial project, which is based on the previous plugin version.

This is a regression, due to the last change I did for you.


Can you just copy the abode line in the generated code, and check it?


On my side, I'll preparing a new release, and I need to update the doc. It should be available in some days.

Etienne

**Comment by mheidt** [comment]
Yes, I debugged into it and when I use BatchLoaderDelegateWithContext, it works for me.
But does it still work, when you generated the classes without the context? Or would you use the old line in that case?

**Comment by etienne-sf** [comment]
I'll always send the context. The developper can thé. Choose to use it or not. 

So the "old line" should not exist any more. 

I understand that you have a workaround. So I'll finish my current job on the plug-in doc, before doing a new release. 

Étienne

**Comment by etienne-sf** [comment]
Oups, correction:

> So the "old line" should not exist any more.

This old line will exist or not, depending on the _generateBatchLoaderEnvironment_ plugin parameter.

**Comment by etienne-sf** [comment]
Check the new release (1.12). It should be solved there.

**Comment by mheidt** [comment]
@etienne-sf 
The code, that was running before now throws a
 Could not resolve placeholder 'graphql.endpoint.url' in value "${graphql.endpoint.url}"
with 1.12

fyi.
searching the value now, which has to be set in the config....

**Comment by mheidt** [comment]
Hm, I think this is only relevant for the client, which I don't use.
Maybe you should give those empty default values:
```
public class GraphQLAutoConfiguration {
    @Value("${graphql.endpoint.url}")
    private String graphqlEndpoint;
    @Value("${graphql.endpoint.subscriptionUrl}")
    private String graphqlSubscriptionEndpoint;
```

**Comment by mheidt** [comment]
And besides that, I still don't get the batchloading working.
The fixed part works. the dataloaderregistry is filled in GraphQLProvider.

But speaking in your example:
```
@Override
	public Member author(DataFetchingEnvironment dataFetchingEnvironment, Topic origin) {
		MemberEntity author = memberRepository.findAuthorOfTopic(origin.getId());
		return mapper.map(author, Member.class);
	}

	@Override
	public CompletableFuture<Member> author(DataFetchingEnvironment dataFetchingEnvironment,
			DataLoader<UUID, Member> dataLoader, Topic origin) {
		// TODO Store in cache the Topic (as it has already been read) to avoid the query below
		TopicEntity topic = topicRepository.findById(origin.getId()).get();

		return dataLoader.load(topic.getAuthorId());
	}
```
I don't want  the former to be called, but the later.
In my case I can only set a breakpoint in the former. There the dataFetchingEnvironment.getDataLoader() is empty, btw.
I don't know how the CompletableFuture returning function is called.

**Comment by etienne-sf** [comment]
> 
> 
> Hm, I think this is only relevant for the client, which I don't use.
> Maybe you should give those empty default values:
> 
> ```
> public class GraphQLAutoConfiguration {
>     @Value("${graphql.endpoint.url}")
>     private String graphqlEndpoint;
>     @Value("${graphql.endpoint.subscriptionUrl}")
>     private String graphqlSubscriptionEndpoint;
> ```

Right.
:(

The combination of plugin parameters is quite high now. There was a missing case, despite all the integration tests.


Please note that I changed the recommanded value for the _copyRuntimeSources_ plugin parameter.

The best is to set it to false.

Then you should remove the _graphql-java-runtime_ dependency. Instead, you should have:

```
		<dependency>
			<groupId>com.graphql-java-generator</groupId>
			<artifactId>graphql-java-server-dependencies</artifactId>
			<version>1.12</version>
			<type>pom</type>
		</dependency>
```

**Comment by etienne-sf** [comment]
> And besides that, I still don't get the batchloading working.
> The fixed part works. the dataloaderregistry is filled in GraphQLProvider.
> 
> [..]

Ok, I released a big version, yesterday, based on a lot of work.

I'll concentrate on this batch loader issue, and add integration tests for that. 
And I'll add a specific page in the doc for that, when that's done.

**Comment by mheidt** [comment]
When I only use the dependency graphql-java-server-dependencies, the build complains, that 
`package com.graphql_java_generator does not exist `
et.al.
is missing.
When I add graphql-maven-plugin, the build succeeds, but when starting up, I get
`No qualifying bean of type 'com.graphql_java_generator.plugin.DocumentParser' available: expected single matching bean but found 2: generateCodeDocumentParser,generateGraphQLSchemaDocumentParser`

**Comment by etienne-sf** [comment]
Yes, because, I think you've done only part of what I explained (but I was not very clear):

You must also set copyRuntimeSources to true. 

Then the code is copied, and you don't need the runtime.

**Comment by mheidt** [comment]
Ok, copyRuntimeSources to true works with dependencies...yes, that was not clear. 
But maybe you should give the  values empty defaults anyways to be more resilient.

I will try to run your sample and hope to be enlightened.

**Comment by etienne-sf** [comment]
Ok, glad it works 

> But maybe you should give the  values empty defaults anyways to be more resilient.

The main issue here is to maintain a compatibility with the previous behavior. 

So all default values makes the plug-in behaves as before.  


So, now: does the batch loader works ?

**Comment by mheidt** [comment]
we are talking about a new client config class, that didn't exist before?
Why don't you use @Value("${graphql.endpoint.url:''}) ?

I just cloned your sample-server...but mvn compile complains about an invalid --release flag I haven't found yet

**Comment by mheidt** [comment]
the pom still is 1.11 and the <release> tag in maven-compiler-plugin seems to be invalid for me...maybe this is new for older java versions? I am old fashioned java 8...

**Comment by mheidt** [comment]
the springboot version in that project didn't work for me either...I am using 2.4.2 now....AND I get the graphql.endpoint.url error...

**Comment by mheidt** [comment]
No, no matter which spring boot version I take, the startup fails with a org.springframework.core.metrics.ApplicationStartup.
Could you please fix the server sample code?

**Comment by mheidt** [comment]
The server sample code doesn't run, but it is built.
Could you explain, why
```
.type(newTypeWiring("Topic").dataFetcher("author", graphQLDataFetchers.dataFetchersDelegateTopicAuthor()))
.type(newTypeWiring("Topic").dataFetcher("author", graphQLDataFetchers.dataFetchersDelegateTopicAuthorWithDataLoader()))
```
there are two wirings for the same?

**Comment by etienne-sf** [comment]
> there are two wirings for the same?

Oups, no. This is a bug. 
But as I said, the dataloader is still used, as I tested on my side. So I think the latest type wiring replace the previous one.



> the pom still is 1.11 and the release tag in maven-compiler-plugin seems to be invalid for me...maybe this is new for older java versions? I am old fashioned java 8...

If you're using the 1.11 plugin, then you can't have the error due to ` @Value("${graphql.endpoint.url:''}") `, as the spring capacities, and 
I think there is an issue with versions, between the plugin version and the runtime version.

> I just cloned your sample-server...but mvn compile complains about an invalid --release flag I haven't found yet

You have to clone the whole project, I think, to have a successful build.


Can you publish this on github, so that I can understand what's you're doing ?

**Comment by mheidt** [comment]
Why do I need more than https://github.com/graphql-java-generator/GraphQL-Forum-Maven-Tutorial-server.git ?

RE wiring:
In your case it works, because the hashcode of author et.al. is different than in my case. In my code the first wiring is used.
I wait, until you fixed this.

And it would be nice, if the server sample is using 1.12. What I wrote before is only valid, if you change to 1.12.

**Comment by mheidt** [comment]
@Etienne,
This is not the only error. So don't build 1.12.1 yet.
Using my project, I copied all generated sources, so that I can change them. I deleted that duplicate line but still no success.
The reason is as I found out earlier: The dataFetchingEnvironment.getDataLoader() in GraphQLDataFetcher is empty and therefore it falls back to the "unbatched" function.
I investigate...

**Comment by mheidt** [comment]
When I autowire the DataLoaderRegistry, and double check it, the batchloading function is called:

```
DataLoader<Long, ShortnameResponseMM> dataLoader = dataFetchingEnvironment.getDataLoader("ShortnameResponseMM"); 
if (dataLoader == null){
            dataLoader =  dataLoaderRegistry.getDataLoader("ShortnameResponseMM");
        }
// This dataLoader may be null. Let's hande that:
if (dataLoader != null) 
```

Please note the type in the comment you generate ("hande")

**Comment by mheidt** [comment]
Ok, I am coming closer. 
We are overriding GraphQLInvocation to be able to log the queries with sleuth

```
@NewSpan("GraphqlInvocation")
public CompletableFuture<ExecutionResult> invoke(@SpanTag(key = "invocationData", resolver = TagValueResolver.class) GraphQLInvocationData graphQLInvocationData,
                                                 WebRequest webRequest) {

    ExecutionInput.Builder executionInputBuilder = ExecutionInput.newExecutionInput()
        .query( graphQLInvocationData.getQuery())
        .operationName(graphQLInvocationData.getOperationName())
        .variables(graphQLInvocationData.getVariables());

    ExecutionInput executionInput = executionInputBuilder
        .context(dataLoaderRegistry)
        .build();
    return graphQL.executeAsync(executionInput);
}
```

That breaks it.
If I deactivate that Bean, the dataloader is in the dataFetchingEnvironment....

**Comment by mheidt** [comment]
And when I extend from DefaultGraphQLInvocation instead and make it look like
```

@Override
    @NewSpan("GraphqlInvocation")
    public CompletableFuture<ExecutionResult> invoke(@SpanTag(key = "invocationData", resolver = TagValueResolver.class) GraphQLInvocationData graphQLInvocationData,
                                                     WebRequest webRequest) {
        return super.invoke(graphQLInvocationData, webRequest);
    }
```

Even when there are two wirings...

**Comment by mheidt** [comment]
The typo is still in 1.12.1
"Let's hande that"

**Comment by etienne-sf** [comment]
Ok, I've seen that this typo is important for you, so I corrected it.
🙂

**Comment by mheidt** [comment]
What can I do? I didn't see any other reason to keep this issue open. :)
Everything else is handled here
https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/68
